[project]
name = "huntgame"
version = "0.0.1"

authors = [
    {name = "pushfoo"}
]

requires-python = ">=3.8"
dependencies = [
    "arcade==3.0.0.dev20"
]

[project.scripts]
huntgame = "huntgame.__main__:main"


[project.optional-dependencies]
dev = [
    'pytest>=7.1,<8'
]
