[project]
name = "huntgame"
version = "0.0.1"

authors = [
    {name = "pushfoo" , email="pushfoo@gmail.com"}
]

requires-python = ">=3.7"
dependencies = [
    "arcade==3.0.0.dev18"
]

[project.scripts]
huntgame = "huntgame.__main__:main"